[[bond]]
source = "tpknam1qrt9a2z6hhutt956ezfkqywdkzqk4cvmthn0yp4zux25e9nhkcscy0pzuh5"
validator = "tnam1q8azt2cpqmc6tr2gvg5v62e4jr0t9327yupaf595"
amount = "85"

[bond.signatures]
tpknam1qrt9a2z6hhutt956ezfkqywdkzqk4cvmthn0yp4zux25e9nhkcscy0pzuh5 = "signam1qqgnsd4epr548fnwtlueg39u5m3zj4jzgcuvsn824ldh6e0s7u3r3duafdyzvsf63pm6epsvg2pm826jdskxcmpe8k5jvr639v87m8cwc4arc6"


[[bond]]
source = "tpknam1qrt9a2z6hhutt956ezfkqywdkzqk4cvmthn0yp4zux25e9nhkcscy0pzuh5"
validator = "tnam1qydvhqdu2q2vrgvju2ngpt6yhrehu525pus6m28p"
amount = "21"

[bond.signatures]
tpknam1qrt9a2z6hhutt956ezfkqywdkzqk4cvmthn0yp4zux25e9nhkcscy0pzuh5 = "signam1qpq907pgenj50cpnvu2re784lef49jmx278nmdlptg8xvw4zcwrhpavl9l7gptvs5rammk0th95m7nskewcl5pam7x92wxc3ucwr04sw90shxe"
